### ISSUE TITLE
unknown mistake

### ISSUE THREAD

**Issue by hihey1** [Monacrylic/Fillet_Rectangles_KiCAD#2]
Monacrylic , the following error occurs when I select a PCB rectangle for rounded corners
in method 'EDA_SHAPE_SetStart', argument 2 of type 'VECTOR2I const &'

hope your answer.

**Comment by NielsDeMoor** [comment]
I have the same issue.

**Comment by Monacrylic** [comment]
Hi @NielsDeMoor @hihey1,
Thanks for pointing out the issue. Could you please tell me which version of KiCAD are you using?

**Comment by NielsDeMoor** [comment]
Hi @Monacrylic , I am using KiCad version 7.0.0-rc2-19 running on macOs Monterey Version 12.6.2

**Comment by hihey1** [comment]
> 

hi，@Monacrylic I am using Kicad version 7.0 running on windows.

**Comment by Monacrylic** [comment]
It seems this is entirely a version issue. This plugin works fine with latest stable release 6.0.11. There are quite a few changes in the scripting API, that make it incompatible with 7.0.x nightly builds.working on adding support for it, thanks!

**Comment by Monacrylic** [comment]
Hi @NielsDeMoor @hihey1,
This plugin is now obsolete. You can achieve the exact same functionality without any plugin by -> Right click on rectangle -> Fillet lines in the latest stable release 7.0.

Thanks for your support!
